### ISSUE TITLE
Access token as environment variable

### ISSUE THREAD

**Issue by tomekrozalski** [storyblok/remix-ultimate-tutorial#2]
That is really impressive how readable and easy Remix Storyblok integration looks :) I wonder only about one issue: how to replace "your-preview-token" by environment variable? The script works on back- and front-end so we cannot do just `process.env.STORYBLOK_TOKEN`. Any thoughts @fgiuliani ?

```
storyblokInit({
  accessToken: "your-preview-token",
  use: [apiPlugin],
  components,
});
```

**Comment by fgiuliani** [comment]
Hey @tomekrozalski thanks for your message and your words! 😃

Have you taken a look at this page in the official Remix documentation?
https://remix.run/docs/en/v1/guides/envvars

**Comment by dohomi** [comment]
Is it best practice to only load with the preview token? should the app not determine based on the inside or outside visual composer to either take preview or public token?

**Comment by fgiuliani** [comment]
hey @tomekrozalski @dohomi @m0t0r sorry for the late response. The DevRel team at Storyblok was pretty busy these last weeks with conferences and events and we didn't have the chance to focus on other tasks.

Let me discuss with the team about this scenario, and what would be a good approach to manage it.

@dohomi as you say, the preview token should be used when working inside the Visual Editor, while the public token is the recommended one for the production environment, the site that the users will visit.

@m0t0r we will evaluate a good approach to take here. Do you have any recommendations on how to face this scenario? Considering the limitation of using env var only on the server-side is not defined by Storyblok SDK itself.

**Comment by alexadark** [comment]
I've just published the last part of the Remix Ultimate tutorial, and this is explained there: https://www.storyblok.com/tp/create-a-preview-environment-for-your-remix-website

**Comment by alexadark** [comment]
I've just published the last part of the Remix Ultimate tutorial, and this is explained there: https://www.storyblok.com/tp/create-a-preview-environment-for-your-remix-website
